# Usa a imagem Node para desenvolvimento
FROM node:22

# Define o diretório de trabalho
WORKDIR /app

# Instala as dependências
COPY package*.json ./
RUN npm install

# Copia o restante dos arquivos
COPY . .

# Expõe a porta 80
EXPOSE 777

# Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "start"]