# Usa uma imagem Python como base
FROM python:3.12

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos para o container
COPY . /app

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expõe a porta 15000 para acesso externo
EXPOSE 15000

# Comando para iniciar a API Flask
CMD ["python", "app.py"]